name: aksana_mobile
description: Aksana Inventory — Mobile App for field operations
publish_to: 'none'
version: 1.3.0+15

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  flutter_riverpod: ^2.5.1
  go_router: ^13.2.0
  mobile_scanner: ^5.2.3
  camera: ^0.11.0+2
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1
  flutter_secure_storage: ^9.0.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
